version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/job_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - spring-boot-postgres
    depends_on:
      PostgreSQL:
        condition: service_healthy

  PostgreSQL:
    image: postgres:15.0
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=job_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - spring-boot-postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
networks:
  spring-boot-postgres:
